### ISSUE TITLE
Masking code in cross attention 

### ISSUE THREAD

**Issue by ShahRutav** [zinengtang/Perceiver_VL#2]
Hi,

Thanks a lot for sharing your work and open sourcing it!

I noticed that there's a `tanh` after filling masked values with `-inf` in cross attention ([here](https://github.com/zinengtang/Perceiver_VL/blob/78e4ead72b8a42be846d3ab4c3af1eba145f73a7/model/modules/perceiver_vl.py#L111)). This makes the attention weights of masked tokens non-zero and essentially using corresponding token information in further layers. 

Please let me know if I am making an error in understanding? Thanks for your time!

**Comment by zinengtang** [comment]
thanks for this catch.
This is indeed an error in model debugging phase.
